/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "light-white": "#f2f2f2",
        "lightest-white-bg": "#efefef",
        "light-gray": "#a8a8a8",
        "lighter-gray": "#bfbfbf",
        "lighter-gray2": "#757575",
        "lightest-gray": "#7B7A7A",
        "medium-gray": "#efefef",
        "dark-gray": "#bcbcbc",
        "bg-gray1": "#E8E9EA",
        "bg-gray2": "#D5D7D8",
        "carbon-black": "#181818",
        "light-black": "#1a1a1a",
        "lighter-black": "#404040",
        "lighter-black2": "#202020",
        "lightest-black": "#545454",
        "light-green": "#01c887",
        "light-pink": "#ff1471",
        "bg-green1": "#A6E1CB",
        "bg-green2": "#7BD9B6",
        "bg-green3": "#00C887",
        "dark-green": "#588970",
        "referral-green1": "#01c887",
        "referral-green2": "#6cdab6",
        "referral-green3": "#9ce1cb",
        "referral-green4": "#b6eedc",
        "referral-green5": "#cdf6e9",
        "cerificate-bg": "#ebfbf6",
        bronze: "#e8c09a",
        silver: "#c2c2c2",
        gold: "#efac09",
        "leadercard-bg": "#00100b",
        "leaderboard-table-bg1": "#cdf6e9",
        "leaderboard-table-bg2": "#b6eedc",
        "leaderboard-table-bg3": "#9ce1cb",
        "leaderboard-table-bg4": "#6cdab6",
        "leaderboard-table-bg5": "#01c887",
        "simulator-counter": "#7fe3c3",
      },
      fontSize: {
        "text-custom-size": "12px",
      },
    },
  },
  plugins: [],
};
